### ISSUE TITLE
Error/Help

### ISSUE THREAD

**Issue by mbazzo** [DougieLawson/RaspberryPi#1]
Hello Friend,

I'm trying to use your code, but this is generating an error that I do not know where it comes from nor how to solve it.

I'm doing the following setup:

i2cdetect -y 1
0 1 2 3 4 5 6 7 8 9 a b c d e f
00 - - - - - - - - - - - - -
10: - - - - - - - - - - - - - - - -
20: - - - - - - - - - - - - - - - -
30: - - - - - - - - - - - - - - - 3f
40 - - - - - - - - - - - - - - - -
50: - - - - - - - - - - - - - - -
60: - - - - - - - - - - - - - - -
70: - - - - - - - -

0x3f is the address of my lcd (connected to an i2c module)

Error is: Unhandled Exception: System.IO.IOException: Error writing to address '63': I2C transaction failed

can you help me?

I tested the commands:
i2cset -y 1 0x3f 0x00
i2cset -y 1 0x3f 0xff

and the LCD responds normally.

Thank you very much.

**Comment by DougieLawson** [comment]
You'll need to update

https://github.com/DougieLawson/RaspberryPi/blob/master/Unified_LCD/pcfLcd.h

Change
```#define PCF_ADDR 0x27```
to
```#define PCF_ADDR 0x3F```
recompile 

pcflcd pcfCG pcf31855 pcf6675 & pcfboth and they should work with your I2C LCD backpack.

Try ```./pcfCG``` or ```./pcflcd``` as a test.

**Comment by mbazzo** [comment]
I was using MonoLCD.
How do I use this new one in C#?

**Comment by DougieLawson** [comment]
You know it helps to tell me that. The C# code is for MONO only. It's never been tested on C# or Win10 IoT.

**Comment by DougieLawson** [comment]
Change the line
```        private static readonly int PCF_ADDR = 0x27;```
to
```        private static readonly int PCF_ADDR = 0x3F;```

Cross your fingers, stick two pencils up your nose, turn round three times, say "Wibble" and hope for the best.

**Comment by mbazzo** [comment]
Still with the same error!

**Comment by laheller** [comment]
@mbazzo

Try my repo:
https://github.com/laheller/RPI_Peripheral
